/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.yallaya.fragments;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiContext;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;
import org.appcelerator.titanium.proxy.TiViewProxy;
import android.app.Activity;


// This proxy can be created by calling Fragments.createExample({message: "hello world"})
@Kroll.proxy(creatableInModule=FragmentsModule.class, propertyAccessors = {

})
public class FragmentFrameProxy extends TiViewProxy
{
	// Standard Debugging variables
	private static final String LCAT = "FragmentFrameProxy";
	private static final boolean DBG = TiConfig.LOGD;
	
	protected FragmentFrame frame = null;
	protected FragmentProxy FragmentProxy = null;
	
	// Constructor
	public FragmentFrameProxy()
	{
		super();
	}
	
	public FragmentFrameProxy(TiContext tiContext)
	{
		this();
	}

	@Override
	public FragmentFrame createView(Activity activity)
	{
		Log.w(LCAT, "FragmentFrame createView");
		this.frame = new FragmentFrame(this);
		
		this.frame.getLayoutParams().autoFillsHeight = true;
		this.frame.getLayoutParams().autoFillsWidth = true;
		
		return this.frame;
	}

	// Handle creation options
	@Override
	public void handleCreationDict(KrollDict options)
	{
		super.handleCreationDict(options);
	}
	
	
	// Methods
	@Kroll.method @Kroll.getProperty
	public int getUid()
	{
		if (this.frame == null) {
			return 0;
		}
		return this.frame.getNativeView().getId();
	}
}
